### ISSUE TITLE
RuntimeError: You can't move a model that has some modules offloaded to cpu or d[BUG_TITLE]

### ISSUE THREAD

**Issue by pranavlal** [luxonis/datadreamer#27]
**Describe the bug**
When I run the below pipeline, I get the following error message.
RuntimeError: You can't move a model that has some modules offloaded to cpu or d
datadreamer --save_dir ~/recognition_dump --class_names person  dog animal car truck cycle motorbike autoriksha truck gun dustbin road stone rock staircase ditch cart box suitcase hanger pan aeroplane airport port buss window glass screen mesh cable wire  table chair sofa television computer laptop printer door window house building gate fens plant tree shrub dashboard bottle spoon fork plate rack dish stove pipe shelf cupboard shirt pajama underwear bed shoes slipper cabinet pole transformer moon sun stars telescope periscope boat submarine driveway elevator --prompts_number 20 --prompt_generator simple --num_objects_range 1 3 --image_generator sdxl --enhance_class_names --device cpu
**Expected behavior**
The pipeline should run.

**Screenshots**

**Environment (please complete the following information):**

- OS: \ arch linux
- Package version:  na

**To Reproduce**
Please provide a minimal reproducible example. This would include:
Once you have data dreamer installed, run the following commands.
datadreamer --save_dir ~/recognition_dump --class_names person  dog animal car truck cycle motorbike autoriksha truck gun dustbin road stone rock staircase ditch cart box suitcase hanger pan aeroplane airport port buss window glass screen mesh cable wire  table chair sofa television computer laptop printer door window house building gate fens plant tree shrub dashboard bottle spoon fork plate rack dish stove pipe shelf cupboard shirt pajama underwear bed shoes slipper cabinet pole transformer moon sun stars telescope periscope boat submarine driveway elevator --prompts_number 20 --prompt_generator simple --num_objects_range 1 3 --image_generator sdxl --enhance_class_names --device cpu

- Used arguments
NA

**Additional context**

**Comment by sokovninn** [comment]
Hi @pranavlal, thank you for the bug report. We will take a look. Could you please provide the full error log?

My guess is that the problem lies in the SynonymGenerator. You can disable it by omitting the `--enhance_class_names` argument, and you won't lose much in terms of dataset quality.

Also, we recommend generating datasets on a GPU, as it's much faster. If you want to create a relatively small dataset, you can use Google Colab: https://colab.research.google.com/github/luxonis/datadreamer/blob/main/examples/generate_dataset_and_train_yolo.ipynb

CC: @HonzaCuhel

**Comment by pranavlal** [comment]
Hi,

 

Many thanks for your answer.

How do I give you the full error log? I captured whatever was displayed on the screen.

**Comment by HonzaCuhel** [comment]
Hi @pranavlal,

I think I know what is the source of the issue. Could you please share the HW specs of the device you ran it on?

Thanks,
Jan

**Comment by pranavlal** [comment]
Hi,

 

Here is relevant system information.

 

cpu:

Architecture:            x86_64                                                                                         

  CPU op-mode(s):        32-bit, 64-bit                                                                                 

  Address sizes:         39 bits physical, 48 bits virtual                                                              

  Byte Order:            Little Endian                                                                                  

CPU(s):                  16                                                                                             

  On-line CPU(s) list:   0-15                                                                                           

Vendor ID:               GenuineIntel                                                                                   

  Model name:            Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz                                                       

    CPU family:          6                                                                                              

    Model:               158                                                                                            

    Thread(s) per core:  2                                                                                              

    Core(s) per socket:  8                                                                                              

    Socket(s):           1                                                                                              

    Stepping:            12                                                                                             

    CPU(s) scaling MHz:  16%                                                                                            

    CPU max MHz:         5000.0000                                                                                      

 

gpu: NVIDIA GeForce GTX 1660 

ram: 32GB

 

Pranav

**Comment by HonzaCuhel** [comment]
Thank you! We are working on the fix as we speak and will get back to you soon!

Best
Jan

**Comment by HonzaCuhel** [comment]
Hi @pranavlal,

we have just released a new version of `DataDreamer` with a fix for your reported bug. Please note that you need a sufficient amount of RAM memory to run the pipeline on the CPU (though your 32GB of RAM should be enough).

Best,
Jan

**Comment by pranavlal** [comment]
Jan,

 

Many thanks, the pipeline is running and the bug does indeed appear to be fixed.

 

I am reporting this after about 6 hours of the pipeline running.

Pranav

**Comment by HonzaCuhel** [comment]
Thank you for reporting. I'll close the issue now; however, if the bug reappears, please reopen the issue.

Best,
Jan
