### ISSUE TITLE
Object not subscriptable

### ISSUE THREAD

**Issue by justincdavis** [luxonis/datadreamer#42]
**Describe the bug**
When using datadreamer on older versions of Python, you get an error that "object is not subscriptable". This comes from the new style of type hinting: tuple[int, int] or list[int] compared to Tuple[int, int] or List[int]

**Expected behavior**
Type annotations should not change the runtime

**Environment (please complete the following information):**

- OS: Windows 11
- Package version: Newest release

**To Reproduce**
Run with older versions of Python such as 3.8

**Additional context**
Simply adding a "from __future__ import annotations" at the top of every package file would be sufficient to solve the issue. I have this change made already and would be happy to issue a pull request. Additionally, I see that Ruff is a pre-commit hook and you can have Ruff check for the __future__ import.

**Comment by sokovninn** [comment]
Hi @justincdavis, thanks for bringing this up. We would appreciate your contribution if it wouldn't take much of your time.
