### ISSUE TITLE
Use DataDreamer for text-only dataset?

### ISSUE THREAD

**Issue by lfoppiano** [luxonis/datadreamer#56]
Hi Datadreamer's team, 
   I've been looking into datadreamer for augmenting one of my datasets, and it seems that this project focuses mostly on images. I'm mostly work with text extraction (NER, RE) and I'm wondering whether it's possible to apply datadreamer to a purely text-based dataset with text and annotations. 

Thank you in advance

**Comment by HonzaCuhel** [comment]
Hi @lfoppiano,

It's certainly an interesting idea, and we might implement it in the future; however, as it would require a lot of time and our focus is on images, such an extension is not planned for the moment.

Kind regards,
Jan

**Comment by lfoppiano** [comment]
I understand. Thanks for the clarification 👍
